export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const UPDATEPROFILE_SUCCESS = 'UPDATEPROFILE_SUCCESS';
export const UPDATEPROFILE_FAIL = 'UPDATEPROFILE_FAIL';
export const UPDATEPROFILE1_SUCCESS = 'UPDATEPROFILE1_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';
export const GOOGLE_LOGIN_FAIL = 'GOOGLE_LOGIN_FAIL';

export const EMAIL_UPDATED = 'EMAIL_UPDATED';
export const EMAIL_UPDATE_FAIL = 'EMAIL_UPDATE_FAIL';

export const PROFILE_UPDATED = 'PROFILE_UPDATED';
export const PROFILE_UPDATED_FAIL = 'PROFILE_UPDATED_FAIL';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const CREATE_CARD_SUCCESS = 'CREATE_CARD_SUCCESS';
export const CREATE_CARD_FAIL = 'CREATE_CARD_FAIL';
export const GET_CARD_SUCCESS = 'GET_CARD_SUCCESS';
export const GET_CARD_FAIL = 'GET_CARD_FAIL';
export const EDIT_CARD_SUCCESS = 'EDIT_CARD_SUCCESS';
export const EDIT_CARD_FAIL = 'EDIT_CARD_FAIL';

export const CREATE_CATALOGUE_SUCCESS = 'CREATE_CATALOGUE_SUCCESS';
export const CREATE_CATALOGUE_FAIL = 'CREATE_CATALOGUE_FAIL';
export const GET_CATALOGUE_SUCCESS = 'GET_CATALOGUE_SUCCESS';
export const GET_CATALOGUE_FAIL = 'GET_CATALOGUE_FAIL';
export const EDIT_CATALOGUE_SUCCESS = 'EDIT_CATALOGUE_SUCCESS';
export const EDIT_CATALOGUE_FAIL = 'EDIT_CATALOGUE_FAIL';

export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_FAIL = 'CREATE_CONTACT_FAIL';

export const WEB_APP_THEME = 'WEB_APP_THEME';
